/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const CountersLazyRouteImport = createFileRoute('/counters')()
const IndexLazyRouteImport = createFileRoute('/')()

const CountersLazyRoute = CountersLazyRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/counters.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/counters': typeof CountersLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/counters': typeof CountersLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/counters': typeof CountersLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/counters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/counters'
  id: '__root__' | '/' | '/counters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CountersLazyRoute: typeof CountersLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/counters': {
      id: '/counters'
      path: '/counters'
      fullPath: '/counters'
      preLoaderRoute: typeof CountersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CountersLazyRoute: CountersLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
